version: '3.7'
services:
  app:
    build:
      context: app
    image: devsecops-app
    ports:
      - 9999:9999
    environment:
      - DATABASE_URL=postgres://app:pass@db:5432/db
    depends_on:
      - db
  db:
    image: postgres:12.3-alpine
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
  tests:
    build:
      context: tests
    image: devsecops-tests
    environment:
      - API_URL=http://app:9999
    depends_on:
      - app
